apiVersion: v1
kind: Pod
metadata:
  name: run-reporter
  namespace: tigera-compliance
  labels:
    k8s-app: compliance-reporter
spec:
  nodeSelector:
    kubernetes.io/os: linux
  restartPolicy: Never
  serviceAccount: tigera-compliance-reporter
  serviceAccountName: tigera-compliance-reporter
  tolerations:
    - key: node-role.kubernetes.io/master
      effect: NoSchedule
  imagePullSecrets:
    - name: tigera-pull-secret
  containers:
  - name: reporter
    # Modify this image name, if you have re-tagged the image and are using a local
    # docker image repository.
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    image: quay.io/tigera/compliance-reporter:$CALICOVERSION
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    env:
      # Modify this value with name of an existing globalreport resource.
      # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - name: TIGERA_COMPLIANCE_REPORT_NAME
      value: $REPORT_NAME
      # Modify these values with the start and end time frame that should be reported on.
      # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - name: TIGERA_COMPLIANCE_REPORT_START_TIME
      # value: <report start time in UTC RFC3339 format, e.g.  2019-03-23T14:20:00Z>
      value: "$START_TIME"
    - name: TIGERA_COMPLIANCE_REPORT_END_TIME
      # value: <report start time in UTC RFC3339 format, e.g. 2019-03-23T15:10:00Z>
      value: "$END_TIME"
      # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - name: LOG_LEVEL
      value: "warning"
    - name: ELASTIC_INDEX_SUFFIX
      value: "$CALICOCLUSTERNAME"
    - name: ELASTIC_SCHEME
      value: https
    - name: ELASTIC_HOST
      value: tigera-secure-es-gateway-http.tigera-elasticsearch.svc
    - name: ELASTIC_PORT
      value: "9200"
    - name: ELASTIC_USER
      valueFrom:
        secretKeyRef:
          name: tigera-ee-compliance-reporter-elasticsearch-access
          key: username
          optional: true
    - name: ELASTIC_PASSWORD
      valueFrom:
        secretKeyRef:
          name: tigera-ee-compliance-reporter-elasticsearch-access
          key: password
          optional: true
    - name: ELASTIC_SSL_VERIFY
      value: "true"
    - name: ELASTIC_CA
      value: /etc/pki/tls/certs/tigera-ca-bundle.crt
    volumeMounts:
    - mountPath: /var/log/calico
      name: var-log-calico
    - mountPath: /etc/pki/tls/certs/
      name: tigera-ca-bundle
      readOnly: true
    livenessProbe:
      httpGet:
        path: /liveness
        port: 9099
        host: localhost
  volumes:
    - name: var-log-calico
      hostPath:
        path: /var/log/calico
        type: DirectoryOrCreate
    - configMap:
        defaultMode: 420
        name: tigera-ca-bundle
      name: tigera-ca-bundle
